# Stable features
edition = "2021"
reorder_imports = true
reorder_modules = true
newline_style = "Unix"
struct_lit_width = 30

# # Unstable features (nightly only)
# unstable_features = true
# force_multiline_blocks = true
# group_imports = "StdExternalCrate"
# imports_granularity = "Crate"
